feat: simplify `Into[Parse]Result` traits by using `anyhow::Result`
This allows solutions to use anyhow for error handling. This was not
previously possible because `anyhow::Error` does not implemented
`std::error::Error`.